source:        .
destination:   ../zhhomestuck.github.io/p

safe:          true
encoding:      UTF-8
exclude:       ["Gemfile*", "README*", "LICENSE*", "*.bat", "*.sh", "*.csv", "*.txt", "*.xml", "scripts"]
markdown_ext:  "html"

plugins:       [jekyll-paginate]

permalink:     /:title.html
paginate:      1

collections:
  pages:
    output: true
    permalink: /:title.html
