plugins:       [jekyll-paginate]
exclude:       ["Gemfile*", "README", "LICENSE.md", "*.bat", "*.csv", "*.txt", "*.xml", "scripts"]
destination:   ../zhhomestuck.github.io/p
markdown_ext:  "html,md"
safe:          true
permalink:     /:title.html
encoding:      UTF-8
paginate:      1

collections:
  pages:
    output: true
    permalink: /:title.html